### ISSUE TITLE
Security Threat and Risk Assessment (STRA) for Landing Zone

### ISSUE THREAD

**Issue by MarisaBC** [bcgov/Cloud-Pathfinder-Azure#29]
**Overview:**
- Security review and recommendations as we develop the landing zone
- Overview of Cloud Adoption Framework and components implementations

**Additional Context:**
- https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/information-security/security-threat-and-risk-assessment

**DoD:**
- [x] Create skeleton structure of assessment
- [ ] Document CAF and CANPUBSEC - referencing Warren's breakdown on choice
- [ ] Incremental information integration and security risk highlights
- [ ] Create formal recommendations
- [ ] Review with team
- [ ] Updates
- [ ] Sign-off
